sudo: required
services:
  - docker

before_install:
  - docker build -t inudog/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true inudog/react-test npm test

after_success:
  - docker build -t inudog/multi-client ./client
  - docker build -t inudog/multi-nginx ./nginx
  - docker build -t inudog/multi-server ./server
  - docker build -t inudog/multi-worker ./worker
  # Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push inudog/multi-client
  - docker push inudog/multi-nginx
  - docker push inudog/multi-server
  - docker push inudog/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'ap-northeast-1'
  app: 'multi-docker'
  env: 'Multi-docker-env'
  bucket_name: 'elasticbeanstalk-ap-northeast-1-772742945665'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY